services:
  database:
    environment:
      POSTGRES_USER: nsr_prod
      POSTGRES_PASSWORD: change_me_prod_password
      POSTGRES_DB: nsr_production
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports: []

  backend:
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"

  frontend:
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

volumes:
  postgres_data_prod:
    driver: local
