services:
  database:
    environment:
      POSTGRES_USER: nsr_dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: nsr_development
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # usa 5433 na m√°quina host para evitar conflito com outros Postgres

  backend:
    env_file:
      - ./backend/.env.dev
    ports:
      - "4000:4000"

  frontend:
    build:
      args:
        - NEXT_PUBLIC_APP_URL=http://localhost:3000
        - NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1
        - API_URL_SERVER=http://backend:4000/api/v1
        - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dcdbwwvtk
        - NEXT_PUBLIC_CLOUDINARY_API_KEY=526431348671521
        - NEXT_PUBLIC_ENVIRONMENT=development
        - NEXT_PUBLIC_PAGBANK_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr+ZqgD892U9/HXsa7XqBZUayPquAfh9xx4iwUbTSUAvTlmiXFQNTp0Bvt/5vK2FhMj39qSv1zi2OuBjvW38q1E374nzx6NNBL5JosV0+SDINTlCG0cmigHuBOyWzYmjgca+mtQu4WczCaApNaSuVqgb8u7Bd9GCOL4YJotvV5+81frlSwQXralhwRzGhj/A57CGPgGKiuPT+AOGmykIGEZsSD9RKkyoKIoc0OS8CPIzdBOtTQCIwrLn2FxI83Clcg55W8gkFSOS6rWNbG5qFZWMll6yl02HtunalHmUlRUL66YeGXdMDC2PuRcmZbGO5a/2tbVppW6mfSWG3NPRpgwIDAQAB
    env_file:
      - ./frontend/.env.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"

volumes:
  postgres_data_dev:
    driver: local
